name: pre-commit

on:
  pull_request:
  # push:
  #   branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install terraform-docs
        env:
          TERRAFORM_DOCS_VERSION: 0.16.0
        run: |
          curl -sL https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-$(uname)-amd64.tar.gz | \
          sudo tar xzf - -C /usr/bin/
      - uses: actions/setup-node@v2
      - name: Install markdownlint-cli
        run: sudo npm install -g markdownlint-cli
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
